### ISSUE TITLE
Lost files and Safe MSC mode suggestion

### ISSUE THREAD

**Issue by andiandi13** [GokulNC/USB_Mass_Storage_Enabler#2]
So I've encountered a big issue on many of my phones and different firmwares. 

When copying files from my computer on my phone with MSC mode, I've lost many files, others were corrupted, others were in LOST.DIR folder but not restorable, and finally, some folders were on the card but not accessible, anyway, a big issue.

Some of these copy issues disappear temporarily when rebooting the phone, when others have no solutions...

But good news : I've found a workaround.
If I unmount my SDCard from the phone before activating Mass Storage mode in the app, there is _no_ problems at all, AMD I've tested that for months !

I've got that idea of unmounting SD Card because on my older phones, before MTP mode was predominant, I used MSC mode and it was **unmounting the SD Card on the phone** , which was _never_ connected on both phone and PC.

So I suggest that you add a SAFE MSC MODE in the home of the app (or as an option, check box...), **which would automatically unmount SDCard as soon as Mass Storage is activated**, and which would REMOUNT Sd Card when MSC mode is deactivated in the app.

I really hope it's feasible, and thank you for that great app.

**Comment by GokulNC** [comment]
Thanks for reporting the issue @andiandi13 .
I already knew that there were issues in a few devices when we write files into External memory card, and I'm also aware of the solution.

The problem is that there is no way to unmount external SDcard programmatically, even if we have root access (atleast that was the case when I tried to do the same 2 years ago).

The only solution would be manually unmounting from Storage Settings by the user before enabling UMS, and manually mount after disabling UMS. 

Also, there'll be a side drawer in the app which contains an option to open "Storage Settings" from where you can directly go to Settings->Storage. This issue was the reason why I added that option in the app.

Please let me know if there's any better way, or if you think the problem is solved, please close the issue.

**Comment by andiandi13** [comment]
Thanks for your reply. I don't really think there's a better solution. I'll keep do the unmounting trick :)
